// "use client";
// import { useRef } from "react";
// import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
// import LinkIcon from "@mui/icons-material/Link";
// import Image from "next/image";

// export default function PayslipPage() {
//   const payslipRef = useRef<HTMLDivElement>(null);

//   const removeUnsupportedColors = (element: HTMLElement) => {
//     const allElements = element.querySelectorAll("*");
//     allElements.forEach((el) => {
//       const htmlEl = el as HTMLElement;
//       ["color", "backgroundColor", "borderColor"].forEach((prop) => {
//         const computed = window.getComputedStyle(htmlEl).getPropertyValue(prop);
//         if (computed.includes("oklch")) {
//           // console.log(Found oklch in ${prop} of:, htmlEl);
//           htmlEl.style.setProperty(prop, "#000", "important");
//         }
//       });
//     });
//   };

//   const handleDownload = async () => {
//     try {
//       if (!payslipRef.current) {
//         console.warn("Payslip element not found!");
//         return;
//       }

//       removeUnsupportedColors(payslipRef.current);

//       const html2pdf = (await import("html2pdf.js")).default;

//       const options = {
//         margin: 0.5,
//         filename: "May-2025-Payslip.pdf",
//         image: { type: "jpeg", quality: 0.98 },
//         html2canvas: {
//           scale: 2,
//           logging: true,
//           dpi: 192,
//           letterRendering: true,
//         },
//         jsPDF: { unit: "in", format: "a4", orientation: "portrait" },
//       };

//       await html2pdf().set(options).from(payslipRef.current).save();
//       console.log("PDF download successful!");
//     } catch (error) {
//       console.error("Error generating PDF:", error);
//     }
//   };

//   return (
//     <>
// <div className="min-h-screen bg-white text-black max-w-7xl min-w-[950px] overflow-x-scroll mt-8 mx-auto" ref={payslipRef} id="pdf">
//   <p className="text-center py-1 bg-[#80b0f84a] text-sm">
//     <VisibilityOutlinedIcon fontSize="small" /> You are viewing the
//     preview version of this payslip
//   </p>
//   <div  className="px-8 pb-10 pt-4">
//     <div className="flex justify-between py-6 ">
//       <Image
//         src="/razerpay.png"
//         width={200}
//         height={400}
//         alt="razerpayimg"
//         className="h-[26px]"
//       ></Image>
//       <div className="border-l pl-5 border-gray-300">
//         <h4 className="text-black font-bold">Payslip: May 2025</h4>
//         <h5 className="text-[12px] flex text-gray-400 items-center">
//           Generated by{" "}
//           <Image
//             src="/razerpay.png"
//             width={200}
//             height={400}
//             alt="razerpayimg"
//             className="h-[14px] w-[100px]"
//           ></Image>
//         </h5>
//       </div>
//     </div>

//     <div className="payslidp-box items-center flex gap-3">
//       <div className="font-semibold">
//         <h5 className="text-gray-500">Net Pay</h5>
//         <h6 className="text-gray-800 text-lg">0</h6>
//       </div>
//       <div className="font-semibold">
//         <p className="text-lg text-gray-500">=</p>
//       </div>
//       <div className="font-semibold border-l-4 border-[#74f845] pl-3">
//         <h5 className="text-gray-500">Gross Pay (A)</h5>
//         <h6 className="text-gray-800 text-lg">+ 0</h6>
//       </div>
//       <div className="font-semibold border-l-4 border-[#f89945] pl-3">
//         <h5 className="text-gray-500">Deductions (B)</h5>
//         <h6 className="text-gray-800 text-lg">- 0</h6>
//       </div>
//     </div>

//     <div className="flex justify-between mt-5">
//       <div className="flex-1/4">
//         <div className="mb-10">
//           <h4 className="text-gray-500 text-[14px]">Name</h4>
//           <h3 className="font-semibold">Shivnilay</h3>
//         </div>
//         <div className="mb-10">
//           <h4 className="text-gray-500 text-[14px]">Regime Opted</h4>
//           <h3 className="font-semibold">New Regime</h3>
//         </div>
//       </div>
//       <div className="flex-3/4">
//         <div className="flex mb-4 relative">
//           <span className="w-[36px] border-t-2 border-l-2 border-[#75f01d] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
//           <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
//           <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#75f01d] rotate-45 absolute left-[-13px] bottom-6"></span>
//           <div className="w-full">
//             <h3 className="font-semibold text flex items-center mb-2">
//               Gross Pay (A)
//               <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#75f01d] rotate-45"></span>
//               <span className="text-gray-400 mt-1 text-[12px] font-normal">
//                 The total money you earned before the deductions
//               </span>
//             </h3>
//             <table className="w-full text-sm overflow-hidden">
//               <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#c7ffd02b_51%,rgba(199,215,255,0)_100%)]">
//                 <tr>
//                   <th className="text-left px-4 py-2">Earnings</th>
//                   <th className="text-center px-4 py-2">Monthly</th>
//                   <th className="text-right px-4 py-2">Total Amount</th>
//                 </tr>
//               </thead>
//               <tbody className="bg-white text-gray-500"></tbody>
//             </table>
//             <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#27d22a0d_51%,#26d8121a_100%)]">
//               <p>Gross Pay</p>
//               <p>0</p>
//             </div>
//           </div>
//         </div>
//         <div className="flex mb-4 relative">
//           <span className="w-[36px] border-t-2 border-l-2 border-[#fc6d0b] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
//           <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
//           <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#fc6d0b] rotate-45 absolute left-[-13px] bottom-6"></span>
//           <div className="w-full">
//             <h3 className="font-semibold text flex items-center mb-2">
//               Deductions (B)
//               <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#fc6d0b] rotate-45"></span>
//               <span className="text-gray-400 mt-1 text-[12px] font-normal">
//                 The amount deducted for taxes and other benefits
//               </span>
//             </h3>
//             <table className="w-full text-sm overflow-hidden">
//               <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]">
//                 <tr>
//                   <th className="text-left px-4 py-2">Deductions</th>
//                   <th className="text-center px-4 py-2">Monthly</th>
//                   <th className="text-right px-4 py-2">Total Amount</th>
//                 </tr>
//               </thead>
//               <tbody className="bg-white text-gray-500"></tbody>
//             </table>
//             <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(83,55,255,0)_0%,#ff96370d_80%,#ffb3371a_100%)]">
//               <p>Total Deductions</p>
//               <p>0</p>
//             </div>
//           </div>
//         </div>
//       </div>
//     </div>

// <div className="mt-5">
//   <div className="flex mb-4 relative">
//     <span className="w-[36px] border-t-2 border-l-2 border-blue-600 rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
//     <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
//     <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#050de8] rotate-45 absolute left-[-13px] bottom-6"></span>
//     <div className="w-full">
//       <h3 className="font-semibold text flex items-center mb-2">
//         Yearly Taxable Income (C){" "}
//         <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#050de8] rotate-45"></span>
//         <span className="text-gray-400 mt-1 text-[12px] font-normal">
//           The money you will earn annually excluding the exemptions
//           you declare Description Gross Exempted Taxable
//         </span>
//       </h3>
// <table className="w-full text-sm overflow-hidden">
//   <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,rgba(199,215,255,0.17)_51%,rgba(199,215,255,0)_100%)]">
//     <tr>
//       <th className="text-left px-4 py-2">Description</th>
//       <th className="text-center px-4 py-2">Gross</th>
//       <th className="text-center px-4 py-2">Exempted</th>
//       <th className="text-right px-4 py-2">Taxable</th>
//     </tr>
//   </thead>
//   <tbody className="bg-white"></tbody>
// </table>
// <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(83,55,255,0)_0%,rgba(83,55,255,0.05)_80%,rgba(83,55,255,0.1)_100%)]">
//   <p>Annual Taxable Salary</p>
//   <p>0</p>
// </div>
//     </div>
//   </div>
// <div className="flex mb-4 relative">
//     <span className="w-[36px] border-t-2 border-l-2 border-[#75f01d] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
//     <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
//     <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#75f01d] rotate-45 absolute left-[-13px] bottom-6"></span>
//     <div className="w-full">
//       <h3 className="font-semibold text flex items-center mb-2">
//         Net Taxable Income (E)
//         <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#75f01d] rotate-45"></span>
//         <span className="text-gray-400 mt-1 text-[12px] font-normal">
//           Your taxes are calculated on this amount after considering
//           all investments you claimed to save taxes
//         </span>
//       </h3>
//       <table className="w-full text-sm overflow-hidden">
//         <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#c7ffd02b_51%,rgba(199,215,255,0)_100%)]">
//           <tr>
//             <th className="text-left px-4 py-2">Details</th>
//             <th className="text-right px-4 py-2">Amount</th>
//           </tr>
//         </thead>
//         <tbody className="bg-white text-gray-500">
//           <tr className="">
//             <th className="text-left px-4 py-2 font-normal">
//               Annual Taxable Salary(C)
//             </th>
//             <th className="text-right px-4 py-2 font-normal">0</th>
//           </tr>
//           <tr className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#c7ffd02b_51%,rgba(199,215,255,0)_100%)]">
//             <th className="text-left px-4 py-2 font-normal">
//               Standard Deductions (Section 16)
//             </th>
//             <th className="text-right px-4 py-2 font-normal">
//               -75,000
//             </th>
//           </tr>
//         </tbody>
//       </table>
//       <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#27d22a0d_51%,#26d8121a_100%)]">
//         <p>Net Taxable Income</p>
//         <p>0</p>
//       </div>
//     </div>
//   </div>
//   <div className="flex mb-4 relative">
//     <span className="w-[36px] border-t-2 border-l-2 border-[#fc6d0b] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
//     <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
//     <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#fc6d0b] rotate-45 absolute left-[-13px] bottom-6"></span>
//     <div className="w-full">
//       <h3 className="font-semibold text flex items-center mb-2">
//         Yearly Taxable Income (C){" "}
//         <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#fc6d0b] rotate-45"></span>
//         <span className="text-gray-400 mt-1 text-[12px] font-normal">
//           The money you will earn annually excluding the exemptions
//           you declare Description Gross Exempted Taxable
//         </span>
//       </h3>
//       <table className="w-full text-sm overflow-hidden">
//         <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]">
//           <tr>
//             <th className="text-left px-4 py-2">Description</th>
//             <th className="text-center px-4 py-2">Gross</th>
//             <th className="text-center px-4 py-2">Exempted</th>
//             <th className="text-right px-4 py-2">Taxable</th>
//           </tr>
//         </thead>
//         <tbody className="bg-white text-gray-500">
//           <tr className="">
//             <th className="text-left px-4 py-2 font-normal">
//               Tax on Taxable Income
//             </th>
//             <th></th>
//             <th></th>
//             <th className="text-right px-4 py-2 font-normal">0</th>
//           </tr>
//           <tr className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]">
//             <th className="text-left px-4 py-2 font-normal">
//               Net Tax
//             </th>
//             <th></th>
//             <th></th>
//             <th className="text-right px-4 py-2 font-normal">0</th>
//           </tr>
//           <tr className="">
//             <th className="text-left px-4 py-2 font-normal">
//               Tax Deducted Till Date (Current Employer)
//             </th>
//             <th></th>
//             <th></th>
//             <th className="text-right px-4 py-2 font-normal">0</th>
//           </tr>
//         </tbody>
//       </table>
//       <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(83,55,255,0)_0%,#ff96370d_80%,#ffb3371a_100%)]">
//         <p>Tax To Be Deducted This Year</p>
//         <p>0</p>
//       </div>
//     </div>
//   </div>
//   <div className="flex mb-4 ">
//     <div className="w-full">
//       <h3 className="font-semibold text flex items-center mb-2">
//         Tax for May 2025
//         <LinkIcon className="mx-2 mt-1 rotate-45" fontSize="small" />
//         <span className="text-gray-400 mt-1 text-[12px] font-normal">
//           Tax to be deducted (F) / No. of payroll executions left in
//           this financial year
//         </span>
//       </h3>
//       <table className="w-full text-sm overflow-hidden">
//         <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]"></thead>
//         <tbody className="bg-white text-gray-500">
//           <tr className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]">
//             <th className="text-left px-4 py-2 font-normal">
//               Tax to be deducted this month
//             </th>
//             <th className="text-right px-4 py-2 font-normal">0</th>
//           </tr>
//         </tbody>
//       </table>
//       <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(83,55,255,0)_0%,#ff96370d_80%,#ffb3371a_100%)]">
//         <p>Tax Deducted This Month </p>
//         <p>0</p>
//       </div>
//     </div>
//   </div>
//   <div className="flex mb-4 relative">
//     <span className="w-[36px] border-t-2 border-l-2 border-[#5337ff] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
//     <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
//     <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#5337ff] rotate-45 absolute left-[-13px] bottom-6"></span>
//     <div className="w-full">
//       <h3 className="font-semibold text flex items-center mb-2">
//         Monthly tax
//         <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#5337ff] rotate-45"></span>
//         <span className="text-gray-400 mt-1 text-[12px] font-normal">
//           Projected TDS for rest of the year are marked with *
//         </span>
//       </h3>
//       <table className="w-full text-sm overflow-hidden">
//         <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]"></thead>
//         <tbody className="bg-white text-gray-500">
//           <tr className="">
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>April 2025</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>May 2025</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>June 2025 *</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>July 2025 *</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>August 2025 *</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>September 2025 *</h3>
//               <h4>0</h4>
//             </th>
//           </tr>
//           <tr className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#b0bffc2b_51%,rgba(199,215,255,0)_100%)]">
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>April 2025</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>May 2025</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>June 2025 *</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>July 2025 *</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>August 2025 *</h3>
//               <h4>0</h4>
//             </th>
//             <th className="text-left px-4 py-2 font-normal">
//               <h3>September 2025 *</h3>
//               <h4>0</h4>
//             </th>
//           </tr>
//         </tbody>
//       </table>

//       <p className="text-[12px] text-gray-500 mt-2">
//         * These may change if there is a change in your income
//       </p>
//     </div>
//   </div>
// </div>
//   </div>
// </div>
//       <div className="mt-10 flex justify-center gap-4">
//         <button
//           onClick={handleDownload}
//           className="bg-blue-600 hover:bg-blue-700 cursor-pointer text-white px-6 py-2 rounded text-sm font-medium"
//         >
//           Download
//         </button>
//         <button
//           onClick={handleDownload}
//           className="bg-blue-600 hover:bg-blue-700 cursor-pointer text-white px-6 py-2 rounded text-sm font-medium"
//         >
//           View Details
//         </button>
//       </div>
//     </>
//   );
// }

"use client";
import { useState, useEffect } from "react";
import {
  PDFDownloadLink,
  Document,
  Page,
  View,
  Text,
  StyleSheet,
  Image as PDFImage,
} from "@react-pdf/renderer";
import Image from "next/image";

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 20,
    fontSize: 12,
    fontFamily: "Helvetica",
  },
  previewBanner: {
    textAlign: "center",
    paddingVertical: 4,
    backgroundColor: "#80b0f84a",
    fontSize: 12,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    marginBottom: 20,
  },
  headerRight: {
    borderLeftWidth: 1,
    borderLeftColor: "#D1D5DB",
    paddingLeft: 20,
  },
  payslipBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 20,
  },
  grossPayBorder: {
    borderLeftWidth: 4,
    borderLeftColor: "#74f845",
    paddingLeft: 12,
  },
  deductionsBorder: {
    borderLeftWidth: 4,
    borderLeftColor: "#f89945",
    paddingLeft: 12,
  },
  sectionContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  employeeInfo: {
    width: "25%",
  },
  earningsDeductions: {
    width: "70%",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  leftBorder: {
    width: 36,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    marginRight: 8,
    marginBottom: 16,
  },
  diamond: {
    width: 6,
    height: 6,
    position: "absolute",
    left: -13,
    bottom: 24,
  },
  table: {
    width: "100%",
    marginBottom: 8,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#c7ffd02b",
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  tableHeaderDeductions: {
    flexDirection: "row",
    backgroundColor: "#eec7c72b",
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  tableCell: {
    flex: 1,
    textAlign: "left",
  },
  tableCellCenter: {
    flex: 1,
    textAlign: "center",
  },
  tableCellRight: {
    flex: 1,
    textAlign: "right",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 20,
    padding: 8,
    backgroundColor: "#27d22a0d",
  },
  totalRowDeductions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 20,
    padding: 8,
    backgroundColor: "#ff96370d",
  },
  monthlyTaxGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  monthlyTaxCell: {
    width: "16%",
    padding: 8,
  },
  noteText: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 8,
  },
});

const PayslipPDF = () => (
  <Document>
    <Page size="A3" style={styles.page}>
      <View style={styles.previewBanner}>
        <Text>You are viewing the preview version of this payslip</Text>
      </View>

      <View
        style={{ paddingHorizontal: 32, paddingBottom: 40, paddingTop: 16 }}
      >
        <View style={styles.header}>
          <PDFImage src="/razerpay.png" style={{ width: 200, height: 26 }} />
          <View style={styles.headerRight}>
            <Text style={{ fontWeight: "bold", color: "#000000" }}>
              Payslip: May 2025
            </Text>
            <Text style={{ fontSize: 12, color: "#9CA3AF" }}>
              Generated by{" "}
              <PDFImage
                src="/razerpay.png"
                style={{ width: 100, height: 14 }}
              />
            </Text>
          </View>
        </View>

        <View style={styles.payslipBox}>
          <View>
            <Text style={{ color: "#6B7280" }}>Net Pay</Text>
            <Text style={{ color: "#1F2937", fontSize: 18 }}>0</Text>
          </View>
          <View>
            <Text style={{ fontSize: 18, color: "#6B7280" }}>=</Text>
          </View>
          <View style={styles.grossPayBorder}>
            <Text style={{ color: "#6B7280" }}>Gross Pay (A)</Text>
            <Text style={{ color: "#1F2937", fontSize: 18 }}>+ 0</Text>
          </View>
          <View style={styles.deductionsBorder}>
            <Text style={{ color: "#6B7280" }}>Deductions (B)</Text>
            <Text style={{ color: "#1F2937", fontSize: 18 }}>- 0</Text>
          </View>
        </View>

        <View style={styles.sectionContainer}>
          <View style={styles.employeeInfo}>
            <View style={{ marginBottom: 40 }}>
              <Text style={{ color: "#6B7280", fontSize: 14 }}>Name</Text>
              <Text style={{ fontWeight: "semibold" }}>Shivnilay</Text>
            </View>
            <View style={{ marginBottom: 40 }}>
              <Text style={{ color: "#6B7280", fontSize: 14 }}>
                Regime Opted
              </Text>
              <Text style={{ fontWeight: "semibold" }}>New Regime</Text>
            </View>
          </View>

          <View style={styles.earningsDeductions}>
            <View
              style={{
                flexDirection: "row",
                marginBottom: 16,
                position: "relative",
              }}
            >
              <View style={[styles.leftBorder, { borderColor: "#75f01d" }]} />
              <View style={{ width: "100%" }}>
                <View style={styles.sectionHeader}>
                  <Text style={{ fontWeight: "semibold" }}>Gross Pay (A)</Text>
                  <View
                    style={[styles.diamond, { backgroundColor: "#75f01d" }]}
                  />
                  <Text
                    style={{ color: "#9CA3AF", fontSize: 12, marginLeft: 8 }}
                  >
                    The total money you earned before the deductions
                  </Text>
                </View>

                <View style={styles.table}>
                  <View style={styles.tableHeader}>
                    <Text style={styles.tableCell}>Earnings</Text>
                    <Text style={styles.tableCellCenter}>Monthly</Text>
                    <Text style={styles.tableCellRight}>Total Amount</Text>
                  </View>
                </View>

                <View style={styles.totalRow}>
                  <Text style={{ fontWeight: "semibold" }}>Gross Pay</Text>
                  <Text style={{ fontWeight: "semibold" }}>0</Text>
                </View>
              </View>
            </View>

            <View
              style={{
                flexDirection: "row",
                marginBottom: 16,
                position: "relative",
              }}
            >
              <View style={[styles.leftBorder, { borderColor: "#fc6d0b" }]} />
              <View style={{ width: "100%" }}>
                <View style={styles.sectionHeader}>
                  <Text style={{ fontWeight: "semibold" }}>Deductions (B)</Text>
                  <View
                    style={[styles.diamond, { backgroundColor: "#fc6d0b" }]}
                  />
                  <Text
                    style={{ color: "#9CA3AF", fontSize: 12, marginLeft: 8 }}
                  >
                    The amount deducted for taxes and other benefits
                  </Text>
                </View>

                <View style={styles.table}>
                  <View style={styles.tableHeaderDeductions}>
                    <Text style={styles.tableCell}>Deductions</Text>
                    <Text style={styles.tableCellCenter}>Monthly</Text>
                    <Text style={styles.tableCellRight}>Total Amount</Text>
                  </View>
                </View>

                <View style={styles.totalRowDeductions}>
                  <Text style={{ fontWeight: "semibold" }}>
                    Total Deductions
                  </Text>
                  <Text style={{ fontWeight: "semibold" }}>0</Text>
                </View>
              </View>
            </View>
          </View>
        </View>

        <View style={{ marginTop: 20 }}>
          <View
            style={{
              flexDirection: "row",
              marginBottom: 16,
              position: "relative",
            }}
          >
            <View style={[styles.leftBorder, { borderColor: "#050de8" }]} />
            <View style={{ width: "100%" }}>
              <View style={styles.sectionHeader}>
                <Text style={{ fontWeight: "semibold" }}>
                  Yearly Taxable Income (C)
                </Text>
                <View
                  style={[styles.diamond, { backgroundColor: "#050de8" }]}
                />
                <Text style={{ color: "#9CA3AF", fontSize: 12, marginLeft: 8 }}>
                  The money you will earn annually excluding the exemptions you
                  declare
                </Text>
              </View>

              <View style={styles.table}>
                <View
                  style={{
                    flexDirection: "row",
                    backgroundColor: "rgba(199,215,255,0.17)",
                    paddingVertical: 8,
                    paddingHorizontal: 16,
                  }}
                >
                  <Text style={styles.tableCell}>Description</Text>
                  <Text style={styles.tableCellCenter}>Gross</Text>
                  <Text style={styles.tableCellCenter}>Exempted</Text>
                  <Text style={styles.tableCellRight}>Taxable</Text>
                </View>
              </View>

              <View
                style={{
                  flexDirection: "row",
                  justifyContent: "flex-end",
                  gap: 20,
                  padding: 8,
                  backgroundColor: "rgba(83,55,255,0.05)",
                }}
              >
                <Text style={{ fontWeight: "semibold" }}>
                  Annual Taxable Salary
                </Text>
                <Text style={{ fontWeight: "semibold" }}>0</Text>
              </View>
            </View>
          </View>

          <View
            style={{
              flexDirection: "row",
              marginBottom: 16,
              position: "relative",
            }}
          >
            <View style={[styles.leftBorder, { borderColor: "#75f01d" }]} />
            <View style={{ width: "100%" }}>
              <View style={styles.sectionHeader}>
                <Text style={{ fontWeight: "semibold" }}>
                  Net Taxable Income (E)
                </Text>
                <View
                  style={[styles.diamond, { backgroundColor: "#75f01d" }]}
                />
                <Text style={{ color: "#9CA3AF", fontSize: 12, marginLeft: 8 }}>
                  Your taxes are calculated on this amount after considering all
                  investments you claimed to save taxes
                </Text>
              </View>
              <View style={styles.table}>
                <View style={styles.tableHeader}>
                  <Text style={styles.tableCell}>Details</Text>
                  <Text style={styles.tableCellRight}>Amount</Text>
                </View>
                <View style={styles.tableRow}>
                  <Text style={styles.tableCell}>Annual Taxable Salary(C)</Text>
                  <Text style={styles.tableCellRight}>0</Text>
                </View>
                <View
                  style={[styles.tableRow, { backgroundColor: "#c7ffd02b" }]}
                >
                  <Text style={styles.tableCell}>
                    Standard Deductions (Section 16)
                  </Text>
                  <Text style={styles.tableCellRight}>-75,000</Text>
                </View>
              </View>

              <View style={styles.totalRow}>
                <Text style={{ fontWeight: "semibold" }}>
                  Net Taxable Income
                </Text>
                <Text style={{ fontWeight: "semibold" }}>0</Text>
              </View>
            </View>
          </View>

          <View
            style={{
              flexDirection: "row",
              marginBottom: 16,
              position: "relative",
            }}
          >
            <View style={[styles.leftBorder, { borderColor: "#fc6d0b" }]} />
            <View style={{ width: "100%" }}>
              <View style={styles.sectionHeader}>
                <Text style={{ fontWeight: "semibold" }}>
                  Yearly Taxable Income (C)
                </Text>
                <View
                  style={[styles.diamond, { backgroundColor: "#fc6d0b" }]}
                />
                <Text style={{ color: "#9CA3AF", fontSize: 12, marginLeft: 8 }}>
                  The money you will earn annually excluding the exemptions you
                  declare
                </Text>
              </View>

              <View style={styles.table}>
                <View style={styles.tableHeaderDeductions}>
                  <Text style={styles.tableCell}>Description</Text>
                  <Text style={styles.tableCellCenter}>Gross</Text>
                  <Text style={styles.tableCellCenter}>Exempted</Text>
                  <Text style={styles.tableCellRight}>Taxable</Text>
                </View>
                <View style={styles.tableRow}>
                  <Text style={styles.tableCell}>Tax on Taxable Income</Text>
                  <Text style={styles.tableCellCenter}></Text>
                  <Text style={styles.tableCellCenter}></Text>
                  <Text style={styles.tableCellRight}>0</Text>
                </View>
                <View
                  style={[styles.tableRow, { backgroundColor: "#eec7c72b" }]}
                >
                  <Text style={styles.tableCell}>Net Tax</Text>
                  <Text style={styles.tableCellCenter}></Text>
                  <Text style={styles.tableCellCenter}></Text>
                  <Text style={styles.tableCellRight}>0</Text>
                </View>
                <View style={styles.tableRow}>
                  <Text style={styles.tableCell}>
                    Tax Deducted Till Date (Current Employer)
                  </Text>
                  <Text style={styles.tableCellCenter}></Text>
                  <Text style={styles.tableCellCenter}></Text>
                  <Text style={styles.tableCellRight}>0</Text>
                </View>
              </View>

              <View style={styles.totalRowDeductions}>
                <Text style={{ fontWeight: "semibold" }}>
                  Tax To Be Deducted This Year
                </Text>
                <Text style={{ fontWeight: "semibold" }}>0</Text>
              </View>
            </View>
          </View>

          <View style={{ marginBottom: 16 }}>
            <View style={styles.sectionHeader}>
              <Text style={{ fontWeight: "semibold" }}>Tax for May 2025</Text>
              <Text style={{ color: "#9CA3AF", fontSize: 12, marginLeft: 8 }}>
                Tax to be deducted (F) / No. of payroll executions left in this
                financial year
              </Text>
            </View>

            <View style={styles.table}>
              <View style={[styles.tableRow, { backgroundColor: "#eec7c72b" }]}>
                <Text style={styles.tableCell}>
                  Tax to be deducted this month
                </Text>
                <Text style={styles.tableCellRight}>0</Text>
              </View>
            </View>

            <View style={styles.totalRowDeductions}>
              <Text style={{ fontWeight: "semibold" }}>
                Tax Deducted This Month
              </Text>
              <Text style={{ fontWeight: "semibold" }}>0</Text>
            </View>
          </View>

          <View
            style={{
              flexDirection: "row",
              marginBottom: 16,
              position: "relative",
            }}
          >
            <View style={[styles.leftBorder, { borderColor: "#5337ff" }]} />
            <View style={{ width: "100%" }}>
              <View style={styles.sectionHeader}>
                <Text style={{ fontWeight: "semibold" }}>Monthly tax</Text>
                <View
                  style={[styles.diamond, { backgroundColor: "#5337ff" }]}
                />
                <Text style={{ color: "#9CA3AF", fontSize: 12, marginLeft: 8 }}>
                  Projected TDS for rest of the year are marked with *
                </Text>
              </View>

              <View style={styles.monthlyTaxGrid}>
                <View style={styles.monthlyTaxCell}>
                  <Text>April 2025</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>May 2025</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>June 2025 *</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>July 2025 *</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>August 2025 *</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>September 2025 *</Text>
                  <Text>0</Text>
                </View>
              </View>

              <View
                style={[
                  styles.monthlyTaxGrid,
                  { backgroundColor: "#b0bffc2b" },
                ]}
              >
                <View style={styles.monthlyTaxCell}>
                  <Text>April 2025</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>May 2025</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>June 2025 *</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>July 2025 *</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>August 2025 *</Text>
                  <Text>0</Text>
                </View>
                <View style={styles.monthlyTaxCell}>
                  <Text>September 2025 *</Text>
                  <Text>0</Text>
                </View>
              </View>

              <Text style={styles.noteText}>
                * These may change if there is a change in your income
              </Text>
            </View>
          </View>
        </View>
      </View>
    </Page>
  </Document>
);

export default function PayslipPage() {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  return (
    <>
      <div>
        <div
          className="min-h-screen bg-white text-black max-w-7xl min-w-[950px] overflow-x-scroll mt-8 mx-auto"
          id="pdf"
        >
          <div className="px-8 pb-10 pt-4">
            <div className="flex justify-between py-6 ">
              <Image
                src="/razerpay.png"
                width={200}
                height={400}
                alt="razerpayimg"
                className="h-[26px]"
              ></Image>
              <div className="border-l pl-5 border-gray-300">
                <h4 className="text-black font-bold">Payslip: May 2025</h4>
                <h5 className="text-[12px] flex text-gray-400 items-center">
                  Generated by{" "}
                  <Image
                    src="/razerpay.png"
                    width={200}
                    height={400}
                    alt="razerpayimg"
                    className="h-[14px] w-[100px]"
                  ></Image>
                </h5>
              </div>
            </div>

            <div className="payslidp-box items-center flex gap-3">
              <div className="font-semibold">
                <h5 className="text-gray-500">Net Pay</h5>
                <h6 className="text-gray-800 text-lg">0</h6>
              </div>
              <div className="font-semibold">
                <p className="text-lg text-gray-500">=</p>
              </div>
              <div className="font-semibold border-l-4 border-[#74f845] pl-3">
                <h5 className="text-gray-500">Gross Pay (A)</h5>
                <h6 className="text-gray-800 text-lg">+ 0</h6>
              </div>
              <div className="font-semibold border-l-4 border-[#f89945] pl-3">
                <h5 className="text-gray-500">Deductions (B)</h5>
                <h6 className="text-gray-800 text-lg">- 0</h6>
              </div>
            </div>

            <div className="flex justify-between mt-5">
              <div className="flex-1/4">
                <div className="mb-10">
                  <h4 className="text-gray-500 text-[14px]">Name</h4>
                  <h3 className="font-semibold">Shivnilay</h3>
                </div>
                <div className="mb-10">
                  <h4 className="text-gray-500 text-[14px]">Regime Opted</h4>
                  <h3 className="font-semibold">New Regime</h3>
                </div>
              </div>
              <div className="flex-3/4">
                <div className="flex mb-4 relative">
                  <span className="w-[36px] border-t-2 border-l-2 border-[#75f01d] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
                  <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
                  <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#75f01d] rotate-45 absolute left-[-13px] bottom-6"></span>
                  <div className="w-full">
                    <h3 className="font-semibold text flex items-center mb-2">
                      Gross Pay (A)
                      <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#75f01d] rotate-45"></span>
                      <span className="text-gray-400 mt-1 text-[12px] font-normal">
                        The total money you earned before the deductions
                      </span>
                    </h3>
                    <table className="w-full text-sm overflow-hidden">
                      <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#c7ffd02b_51%,rgba(199,215,255,0)_100%)]">
                        <tr>
                          <th className="text-left px-4 py-2">Earnings</th>
                          <th className="text-center px-4 py-2">Monthly</th>
                          <th className="text-right px-4 py-2">Total Amount</th>
                        </tr>
                      </thead>
                      <tbody className="bg-white text-gray-500"></tbody>
                    </table>
                    <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#27d22a0d_51%,#26d8121a_100%)]">
                      <p>Gross Pay</p>
                      <p>0</p>
                    </div>
                  </div>
                </div>
                <div className="flex mb-4 relative">
                  <span className="w-[36px] border-t-2 border-l-2 border-[#fc6d0b] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
                  <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
                  <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#fc6d0b] rotate-45 absolute left-[-13px] bottom-6"></span>
                  <div className="w-full">
                    <h3 className="font-semibold text flex items-center mb-2">
                      Deductions (B)
                      <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#fc6d0b] rotate-45"></span>
                      <span className="text-gray-400 mt-1 text-[12px] font-normal">
                        The amount deducted for taxes and other benefits
                      </span>
                    </h3>
                    <table className="w-full text-sm overflow-hidden">
                      <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]">
                        <tr>
                          <th className="text-left px-4 py-2">Deductions</th>
                          <th className="text-center px-4 py-2">Monthly</th>
                          <th className="text-right px-4 py-2">Total Amount</th>
                        </tr>
                      </thead>
                      <tbody className="bg-white text-gray-500"></tbody>
                    </table>
                    <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(83,55,255,0)_0%,#ff96370d_80%,#ffb3371a_100%)]">
                      <p>Total Deductions</p>
                      <p>0</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-5">
              <div className="flex mb-4 relative">
                <span className="w-[36px] border-t-2 border-l-2 border-blue-600 rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
                <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
                <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#050de8] rotate-45 absolute left-[-13px] bottom-6"></span>
                <div className="w-full">
                  <h3 className="font-semibold text flex items-center mb-2">
                    Yearly Taxable Income (C){" "}
                    <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#050de8] rotate-45"></span>
                    <span className="text-gray-400 mt-1 text-[12px] font-normal">
                      The money you will earn annually excluding the exemptions
                      you declare Description Gross Exempted Taxable
                    </span>
                  </h3>
                  <table className="w-full text-sm overflow-hidden">
                    <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,rgba(199,215,255,0.17)_51%,rgba(199,215,255,0)_100%)]">
                      <tr>
                        <th className="text-left px-4 py-2">Description</th>
                        <th className="text-center px-4 py-2">Gross</th>
                        <th className="text-center px-4 py-2">Exempted</th>
                        <th className="text-right px-4 py-2">Taxable</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white"></tbody>
                  </table>
                  <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(83,55,255,0)_0%,rgba(83,55,255,0.05)_80%,rgba(83,55,255,0.1)_100%)]">
                    <p>Annual Taxable Salary</p>
                    <p>0</p>
                  </div>
                </div>
              </div>
              <div className="flex mb-4 relative">
                <span className="w-[36px] border-t-2 border-l-2 border-[#75f01d] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
                <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
                <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#75f01d] rotate-45 absolute left-[-13px] bottom-6"></span>
                <div className="w-full">
                  <h3 className="font-semibold text flex items-center mb-2">
                    Net Taxable Income (E)
                    <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#75f01d] rotate-45"></span>
                    <span className="text-gray-400 mt-1 text-[12px] font-normal">
                      Your taxes are calculated on this amount after considering
                      all investments you claimed to save taxes
                    </span>
                  </h3>
                  <table className="w-full text-sm overflow-hidden">
                    <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#c7ffd02b_51%,rgba(199,215,255,0)_100%)]">
                      <tr>
                        <th className="text-left px-4 py-2">Details</th>
                        <th className="text-right px-4 py-2">Amount</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white text-gray-500">
                      <tr className="">
                        <th className="text-left px-4 py-2 font-normal">
                          Annual Taxable Salary(C)
                        </th>
                        <th className="text-right px-4 py-2 font-normal">0</th>
                      </tr>
                      <tr className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#c7ffd02b_51%,rgba(199,215,255,0)_100%)]">
                        <th className="text-left px-4 py-2 font-normal">
                          Standard Deductions (Section 16)
                        </th>
                        <th className="text-right px-4 py-2 font-normal">
                          -75,000
                        </th>
                      </tr>
                    </tbody>
                  </table>
                  <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#27d22a0d_51%,#26d8121a_100%)]">
                    <p>Net Taxable Income</p>
                    <p>0</p>
                  </div>
                </div>
              </div>
              <div className="flex mb-4 relative">
                <span className="w-[36px] border-t-2 border-l-2 border-[#fc6d0b] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
                <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
                <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#fc6d0b] rotate-45 absolute left-[-13px] bottom-6"></span>
                <div className="w-full">
                  <h3 className="font-semibold text flex items-center mb-2">
                    Yearly Taxable Income (C){" "}
                    <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#fc6d0b] rotate-45"></span>
                    <span className="text-gray-400 mt-1 text-[12px] font-normal">
                      The money you will earn annually excluding the exemptions
                      you declare Description Gross Exempted Taxable
                    </span>
                  </h3>
                  <table className="w-full text-sm overflow-hidden">
                    <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]">
                      <tr>
                        <th className="text-left px-4 py-2">Description</th>
                        <th className="text-center px-4 py-2">Gross</th>
                        <th className="text-center px-4 py-2">Exempted</th>
                        <th className="text-right px-4 py-2">Taxable</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white text-gray-500">
                      <tr className="">
                        <th className="text-left px-4 py-2 font-normal">
                          Tax on Taxable Income
                        </th>
                        <th></th>
                        <th></th>
                        <th className="text-right px-4 py-2 font-normal">0</th>
                      </tr>
                      <tr className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]">
                        <th className="text-left px-4 py-2 font-normal">
                          Net Tax
                        </th>
                        <th></th>
                        <th></th>
                        <th className="text-right px-4 py-2 font-normal">0</th>
                      </tr>
                      <tr className="">
                        <th className="text-left px-4 py-2 font-normal">
                          Tax Deducted Till Date (Current Employer)
                        </th>
                        <th></th>
                        <th></th>
                        <th className="text-right px-4 py-2 font-normal">0</th>
                      </tr>
                    </tbody>
                  </table>
                  <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(83,55,255,0)_0%,#ff96370d_80%,#ffb3371a_100%)]">
                    <p>Tax To Be Deducted This Year</p>
                    <p>0</p>
                  </div>
                </div>
              </div>
              <div className="flex mb-4 ">
                <div className="w-full">
                  <h3 className="font-semibold text flex items-center mb-2">
                    Tax for May 2025
                    <span className="text-gray-400 mt-1 text-[12px] font-normal">
                      Tax to be deducted (F) / No. of payroll executions left in
                      this financial year
                    </span>
                  </h3>
                  <table className="w-full text-sm overflow-hidden">
                    <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]"></thead>
                    <tbody className="bg-white text-gray-500">
                      <tr className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]">
                        <th className="text-left px-4 py-2 font-normal">
                          Tax to be deducted this month
                        </th>
                        <th className="text-right px-4 py-2 font-normal">0</th>
                      </tr>
                    </tbody>
                  </table>
                  <div className="flex justify-end gap-5 font-semibold p-2 bg-[linear-gradient(90deg,rgba(83,55,255,0)_0%,#ff96370d_80%,#ffb3371a_100%)]">
                    <p>Tax Deducted This Month </p>
                    <p>0</p>
                  </div>
                </div>
              </div>
              <div className="flex mb-4 relative">
                <span className="w-[36px] border-t-2 border-l-2 border-[#5337ff] rounded-l-2xl h-auto mt-3 mr-2 mb-4"></span>
                <span className="bottom-0 left-0 flex absolute h-[40px] w-[20px] bg-white"></span>
                <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#5337ff] rotate-45 absolute left-[-13px] bottom-6"></span>
                <div className="w-full">
                  <h3 className="font-semibold text flex items-center mb-2">
                    Monthly tax
                    <span className="w-[6px] h-[6px] mt-1 mx-3 bg-[#5337ff] rotate-45"></span>
                    <span className="text-gray-400 mt-1 text-[12px] font-normal">
                      Projected TDS for rest of the year are marked with *
                    </span>
                  </h3>
                  <table className="w-full text-sm overflow-hidden">
                    <thead className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#eec7c72b_51%,rgba(199,215,255,0)_100%)]"></thead>
                    <tbody className="bg-white text-gray-500">
                      <tr className="">
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>April 2025</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>May 2025</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>June 2025 *</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>July 2025 *</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>August 2025 *</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>September 2025 *</h3>
                          <h4>0</h4>
                        </th>
                      </tr>
                      <tr className="bg-[linear-gradient(90deg,rgba(199,215,255,0)_0%,#b0bffc2b_51%,rgba(199,215,255,0)_100%)]">
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>April 2025</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>May 2025</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>June 2025 *</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>July 2025 *</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>August 2025 *</h3>
                          <h4>0</h4>
                        </th>
                        <th className="text-left px-4 py-2 font-normal">
                          <h3>September 2025 *</h3>
                          <h4>0</h4>
                        </th>
                      </tr>
                    </tbody>
                  </table>

                  <p className="text-[12px] text-gray-500 mt-2">
                    * These may change if there is a change in your income
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-10 flex justify-center gap-4">
          {isClient && (
            <PDFDownloadLink
              document={<PayslipPDF />}
              fileName="May-2025-Payslip.pdf"
              className="bg-blue-600 hover:bg-blue-700 cursor-pointer text-white px-6 py-2 rounded text-sm font-medium"
            >
              {({ loading }) => (loading ? "Loading document..." : "Download")}
            </PDFDownloadLink>
          )}
          <button className="bg-blue-600 hover:bg-blue-700 cursor-pointer text-white px-6 py-2 rounded text-sm font-medium">
            View Details
          </button>
        </div>
      </div>
    </>
  );
}
