"use client";
import { useRef } from "react";
import { Svg, Path } from "@react-pdf/renderer";
import {
  Document,
  Page,
  Text,
  View,
  PDFViewer,
  pdf,
  Image,
} from "@react-pdf/renderer";

const VisibilityIcon = () => (
  <Svg viewBox="0 0 24 24" width="12" height="12" style={{ marginRight: 4 }}>
    <Path
      d="M12 6c-5 0-9 6-9 6s4 6 9 6 9-6 9-6-4-6-9-6zm0 10a4 4 0 1 1 0-8 4 4 0 0 1 0 8z"
      fill="#000"
    />
    <Path d="M12 10a2 2 0 1 0 0 4 2 2 0 0 0 0-4z" fill="#000" />
  </Svg>
);

const PayslipDocument = () => {
  return (
    <Document>
      <Page size="A4">
        <View
          style={{
            backgroundColor: "#80b0f84a",
            padding: 5,
            color: "#737373",
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
            marginBottom: 6,
          }}
        >
          <VisibilityIcon />
          <Text style={{ fontSize: 11 }}>
            You are viewing the preview version of this payslip
          </Text>
        </View>

        <View>
          <View
            style={{
              flexDirection: "row",
              alignItems: "center",
              justifyContent: "space-between",
              paddingVertical: 16,
              padding: "8px 12px",
            }}
          >
            <Image
              src="/logo.png"
              style={{ width: 40, height: 40, marginRight: 20 }}
            />

            <View
              style={{
                borderLeftWidth: 1.5,
                borderColor: "#ccc",
                paddingLeft: 10,
                marginRight: "6px",
              }}
            >
              <Text
                style={{ fontSize: 14, fontWeight: "semibold", color: "#000" }}
              >
                Payslip: May 2025
              </Text>
              <View
                style={{
                  flexDirection: "row",
                  alignItems: "center",
                  marginTop: 4,
                }}
              >
                <Text style={{ fontSize: 10, color: "#666", marginRight: 6 }}>
                  Generated by
                </Text>
                <Text
                  style={{
                    fontSize: "11px",
                    fontWeight: "bold",
                    color: "#f4a12e",
                  }}
                >
                  ENS Enterprises
                </Text>
              </View>
            </View>
          </View>
        </View>

        <View style={{ position: "relative" }}>
          <Image
            src="/payslip-bg.png"
            style={{
              width: "100%",
              height: "100px",
              marginRight: 20,
              objectFit: "cover",
            }}
          />
          <View
            style={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "center",
              alignItems: "center",
              position: "absolute",
              top: "35%",
              left: "25%",
            }}
          >
            <View style={{ margin: "0 12px" }}>
              <Text
                style={{
                  color: "#6c6c6c",
                  fontSize: "10px",
                  marginBottom: "4px",
                }}
              >
                Net Pay
              </Text>
              <Text style={{ color: "#6c6c6c", fontSize: "10px" }}>0</Text>
            </View>
            <View style={{ margin: "0 12px" }}>
              <Text style={{ color: "6c6c6c" }}>=</Text>
            </View>
            <View
              style={{
                margin: "0 12px",
                borderLeft: "2px solid green",
                paddingLeft: "12px",
              }}
            >
              <Text
                style={{
                  color: "#6c6c6c",
                  fontSize: "10px",
                  marginBottom: "4px",
                }}
              >
                Gross Pay (A)
              </Text>
              <Text style={{ color: "#8c8c8f", fontSize: "10px" }}>+ 0</Text>
            </View>
            <View
              style={{
                margin: "0 12px",
                borderLeft: "2px solid red",
                paddingLeft: "12px",
              }}
            >
              <Text
                style={{
                  color: "#6c6c6c",
                  fontSize: "10px",
                  marginBottom: "4px",
                }}
              >
                Deductions (B)
              </Text>
              <Text style={{ color: "#6c6c6c", fontSize: "10px" }}>- 0</Text>
            </View>
          </View>
        </View>

        <View
          style={{
            display: "flex",
            flexDirection: "row",
            padding: "10px 24px",
          }}
        >
          <View style={{ width: "30%" }}>
            <Text
              style={{
                fontSize: "10px",
                marginBottom: "3px",
                color: "#a2a8a1",
              }}
            >
              Name
            </Text>
            <Text style={{ fontSize: "10px", marginBottom: "26px" }}>
              Shivnilay
            </Text>
            <Text
              style={{
                fontSize: "10px",
                marginBottom: "3px",
                color: "#a2a8a1",
              }}
            >
              Regime Opted
            </Text>
            <Text style={{ fontSize: "10px", marginBottom: "3px" }}>
              New Regime
            </Text>
          </View>

          <View style={{ width: "70%" }}>
            <View
              style={{
                display: "flex",
                flexDirection: "row",
                alignItems: "flex-start",
                marginBottom: "20px",
                width: "100%",
                position: "relative",
              }}
            >
              <Text
                style={{
                  borderLeftWidth: 1.5,
                  borderTopWidth: 1.5,
                  width: "34px",
                  marginTop: "6px",
                  marginRight: "4px",
                  height: "70%",
                  borderColor: "#3fe51a",
                  borderTopLeftRadius: 16,
                }}
              ></Text>
              <Text
                style={{
                  width: "5px",
                  height: "5px",
                  backgroundColor: "#3fe51a",
                  transform: "rotate(45deg)",
                  margin: "0 8px 0 8px",
                  position: "absolute",
                  left: "-10px",
                  bottom: "6px",
                }}
              ></Text>
              <View style={{ width: "100%" }}>
                <View
                  style={{
                    display: "flex",
                    flexDirection: "row",
                    alignItems: "center",
                  }}
                >
                  <Text style={{ fontSize: "11px", fontWeight: "500" }}>
                    Gross Pay (A)
                  </Text>
                  <Text
                    style={{
                      width: "5px",
                      height: "5px",
                      backgroundColor: "#3fe51a",
                      transform: "rotate(45deg)",
                      margin: "0 8px 0 8px",
                    }}
                  ></Text>
                  <Text
                    style={{
                      fontSize: "10px",
                      color: "#767473",
                      letterSpacing: "0.25px",
                    }}
                  >
                    The total money you earned before the deductions
                  </Text>
                </View>
                <View
                  style={{
                    width: "100%",
                    fontSize: "12px",
                    overflow: "hidden",
                    marginTop: "10px",
                    marginLeft: "-15px",
                  }}
                >
                  <View
                    style={{
                      flexDirection: "row",
                      backgroundColor: "rgba(199,215,255,0.09)",
                      paddingVertical: 6,
                      paddingHorizontal: 12,
                      width: "100%",
                    }}
                  >
                    <Text style={{ flex: 2, textAlign: "left" }}>Earnings</Text>
                    <Text style={{ flex: 1, textAlign: "center" }}>
                      Monthly
                    </Text>
                    <Text style={{ flex: 1, textAlign: "right" }}>
                      Total Amount
                    </Text>
                  </View>

                  <View
                    style={{
                      flexDirection: "row",
                      justifyContent: "flex-end",
                      gap: 20,
                      fontWeight: 400,
                      padding: 8,
                      backgroundColor: "rgba(83,55,255,0.05)",
                    }}
                  >
                    <Text>Gross Pay </Text>
                    <Text>0</Text>
                  </View>
                </View>
              </View>
            </View>
            <View
              style={{
                display: "flex",
                flexDirection: "row",
                alignItems: "flex-start",
                marginBottom: "20px",
                position: "relative",
              }}
            >
              <Text
                style={{
                  borderLeftWidth: 1.5,
                  borderTopWidth: 1.5,
                  width: "34px",
                  marginTop: "6px",
                  marginRight: "4px",
                  height: "70%",
                  borderColor: "#e5291a",
                  borderTopLeftRadius: 16,
                }}
              ></Text>
              <Text
                style={{
                  width: "5px",
                  height: "5px",
                  backgroundColor: "#e5291a",
                  transform: "rotate(45deg)",
                  margin: "0 8px 0 8px",
                  position: "absolute",
                  left: "-10px",
                  bottom: "6px",
                }}
              ></Text>
              <View style={{ width: "100%" }}>
                <View
                  style={{
                    display: "flex",
                    flexDirection: "row",
                    alignItems: "center",
                  }}
                >
                  <Text style={{ fontSize: "11px", fontWeight: "500" }}>
                    Deductions (B)
                  </Text>
                  <Text
                    style={{
                      width: "5px",
                      height: "5px",
                      backgroundColor: "#e5291a",
                      transform: "rotate(45deg)",
                      margin: "0 8px 0 8px",
                    }}
                  ></Text>
                  <Text
                    style={{
                      fontSize: "10px",
                      color: "#767473",
                      letterSpacing: "0.25px",
                    }}
                  >
                    The amount deducted for taxes and other benefits
                  </Text>
                </View>
                <View
                  style={{
                    width: "100%",
                    fontSize: "12px",
                    overflow: "hidden",
                    marginTop: "10px",
                    marginLeft: "-15px",
                  }}
                >
                  <View
                    style={{
                      flexDirection: "row",
                      backgroundColor: "rgba(199,215,255,0.09)",
                      paddingVertical: 6,
                      paddingHorizontal: 12,
                      width: "100%",
                    }}
                  >
                    <Text style={{ flex: 2, textAlign: "left" }}>
                      Deductions
                    </Text>
                    <Text style={{ flex: 1, textAlign: "center" }}>
                      Monthly
                    </Text>
                    <Text style={{ flex: 1, textAlign: "right" }}>
                      Total Amount
                    </Text>
                  </View>
                  <View
                    style={{
                      flexDirection: "row",
                      justifyContent: "flex-end",
                      gap: 20,
                      fontWeight: 400,
                      padding: 8,
                      backgroundColor: "rgba(83,55,255,0.05)",
                    }}
                  >
                    <Text>Total Deductions</Text>
                    <Text>0</Text>
                  </View>
                </View>
              </View>
            </View>
          </View>
        </View>

        <View style={{ marginTop: "10px", padding: "0 24px" }}>
          <View
            style={{
              display: "flex",
              flexDirection: "row",
              alignItems: "flex-start",
              marginBottom: "20px",
              position: "relative",
            }}
          >
            <Text
              style={{
                borderLeftWidth: 1.5,
                borderTopWidth: 1.5,
                width: "34px",
                marginTop: "6px",
                marginRight: "4px",
                height: "70%",
                borderColor: "#1a36e5",
                borderTopLeftRadius: 16,
              }}
            ></Text>
            <Text
              style={{
                width: "5px",
                height: "5px",
                backgroundColor: "#1a36e5",
                transform: "rotate(45deg)",
                margin: "0 8px 0 8px",
                position: "absolute",
                left: "-10px",
                bottom: "6px",
              }}
            ></Text>
            <View style={{ width: "100%" }}>
              <View
                style={{
                  display: "flex",
                  flexDirection: "row",
                  alignItems: "center",
                }}
              >
                <Text style={{ fontSize: "11px", fontWeight: "500" }}>
                  Tax for 2025 - 26
                </Text>
                <Text
                  style={{
                    width: "5px",
                    height: "5px",
                    backgroundColor: "#1a36e5",
                    transform: "rotate(45deg)",
                    margin: "0 8px 0 8px",
                  }}
                ></Text>
                <Text
                  style={{
                    fontSize: "10px",
                    color: "#767473",
                    letterSpacing: "0.25px",
                  }}
                >
                  Tax will be deducted on this Net Taxable Salary after all
                  exemptions
                </Text>
              </View>
              <View
                style={{
                  width: "100%",
                  fontSize: "12px",
                  overflow: "hidden",
                  marginTop: "10px",
                  marginLeft: "-15px",
                }}
              >
                <View
                  style={{
                    flexDirection: "row",
                    backgroundColor: "rgba(199,215,255,0.09)",
                    paddingVertical: 6,
                    paddingHorizontal: 12,
                    width: "100%",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>
                    Description
                  </Text>
                  <Text style={{ flex: 1, textAlign: "center" }}>Gross</Text>
                  <Text style={{ flex: 1, textAlign: "center" }}>Exempted</Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>Taxable</Text>
                </View>
                <View
                  style={{
                    flexDirection: "row",
                    justifyContent: "flex-end",
                    gap: 20,
                    fontWeight: 400,
                    padding: 8,
                    backgroundColor: "rgba(83,55,255,0.05)",
                  }}
                >
                  <Text>Annual Taxable Salary</Text>
                  <Text>0</Text>
                </View>
              </View>
            </View>
          </View>
          <View
            style={{
              display: "flex",
              flexDirection: "row",
              alignItems: "flex-start",
              marginBottom: "20px",
              position: "relative",
            }}
          >
            <Text
              style={{
                borderLeftWidth: 1.5,
                borderTopWidth: 1.5,
                width: "30px",
                marginTop: "6px",
                marginRight: "4px",
                height: "70%",
                borderColor: "#3fe51a",
                borderTopLeftRadius: 16,
              }}
            ></Text>
            <Text
              style={{
                width: "5px",
                height: "5px",
                backgroundColor: "#3fe51a",
                transform: "rotate(45deg)",
                margin: "0 8px 0 8px",
                position: "absolute",
                left: "-10px",
                bottom: "25px",
              }}
            ></Text>
            <View style={{ width: "100%" }}>
              <View
                style={{
                  display: "flex",
                  flexDirection: "row",
                  alignItems: "center",
                }}
              >
                <Text style={{ fontSize: "11px", fontWeight: "500" }}>
                  Net Taxable Income (E)
                </Text>
                <Text
                  style={{
                    width: "5px",
                    height: "5px",
                    backgroundColor: "#3fe51a",
                    transform: "rotate(45deg)",
                    margin: "0 8px 0 8px",
                  }}
                ></Text>
                <Text
                  style={{
                    fontSize: "10px",
                    color: "#767473",
                    letterSpacing: "0.25px",
                  }}
                >
                  Your taxes are calculated on this amount after considering all
                  investments
                </Text>
              </View>
              <View
                style={{
                  width: "100%",
                  fontSize: "12px",
                  overflow: "hidden",
                  marginTop: "10px",
                  marginLeft: "-15px",
                }}
              >
                <View
                  style={{
                    flexDirection: "row",
                    backgroundColor: "rgba(199, 215, 255, 0.09)",
                    paddingVertical: 6,
                    paddingHorizontal: 12,
                    width: "100%",
                    marginBottom: "10px",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>Details</Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>Amount</Text>
                </View>

                <View
                  style={{
                    flexDirection: "row",
                    fontSize: "11px",
                    padding: "0 8px",
                    width: "100%",
                    marginBottom: "8px",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>
                    Annual Taxable Salary(C)
                  </Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>0</Text>
                </View>

                <View
                  style={{
                    flexDirection: "row",
                    fontSize: "11px",
                    padding: "0 8px",
                    width: "100%",
                    marginBottom: "8px",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>
                    Standard Deductions (Section 16)
                  </Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>-75,000</Text>
                </View>
                <View
                  style={{
                    flexDirection: "row",
                    fontSize: "11px",
                    padding: "0 8px",
                    width: "100%",
                    marginBottom: "8px",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>
                    Net Taxable Income
                  </Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>0</Text>
                </View>
                <View
                  style={{
                    flexDirection: "row",
                    justifyContent: "flex-end",
                    gap: 20,
                    fontSize: "12px",
                    fontWeight: 500,
                    padding: 8,
                    backgroundColor: "rgba(83,55,255,0.05)",
                  }}
                >
                  <Text>Net Taxable Income </Text>
                  <Text>0</Text>
                </View>
              </View>
            </View>
          </View>
          <View
            style={{
              display: "flex",
              flexDirection: "row",
              alignItems: "flex-start",
              marginBottom: "20px",
              position: "relative",
            }}
          >
            <Text
              style={{
                borderLeftWidth: 1.5,
                borderTopWidth: 1.5,
                width: "34px",
                marginTop: "6px",
                marginRight: "4px",
                height: "70%",
                borderColor: "#e5291a",
                borderTopLeftRadius: 16,
              }}
            ></Text>
            <Text
              style={{
                width: "5px",
                height: "5px",
                backgroundColor: "#e5291a",
                transform: "rotate(45deg)",
                margin: "0 8px 0 8px",
                position: "absolute",
                left: "-10px",
                bottom: "25px",
              }}
            ></Text>
            <View style={{ width: "100%" }}>
              <View
                style={{
                  display: "flex",
                  flexDirection: "row",
                  alignItems: "center",
                }}
              >
                <Text style={{ fontSize: "11px", fontWeight: "500" }}>
                  Tax for 2025 - 26
                </Text>
                <Text
                  style={{
                    width: "5px",
                    height: "5px",
                    backgroundColor: "#e5291a",
                    transform: "rotate(45deg)",
                    margin: "0 8px 0 8px",
                  }}
                ></Text>
                <Text
                  style={{
                    fontSize: "10px",
                    color: "#767473",
                    letterSpacing: "0.25px",
                  }}
                >
                  Tax will be deducted on this Net Taxable Salary after all
                  exemptions
                </Text>
              </View>
              <View
                style={{
                  width: "100%",
                  fontSize: "12px",
                  overflow: "hidden",
                  marginTop: "10px",
                  marginLeft: "-15px",
                }}
              >
                <View
                  style={{
                    flexDirection: "row",
                    backgroundColor: "rgba(199, 215, 255, 0.09)",
                    paddingVertical: 6,
                    paddingHorizontal: 12,
                    width: "100%",
                    marginBottom: "10px",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>Details</Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>Amount</Text>
                </View>

                <View
                  style={{
                    flexDirection: "row",
                    fontSize: "11px",
                    padding: "0 8px",
                    width: "100%",
                    marginBottom: "8px",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>
                    Tax on Taxable Income
                  </Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>0</Text>
                </View>

                <View
                  style={{
                    flexDirection: "row",
                    fontSize: "11px",
                    padding: "0 8px",
                    width: "100%",
                    marginBottom: "8px",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>Net Tax</Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>0</Text>
                </View>
                <View
                  style={{
                    flexDirection: "row",
                    fontSize: "11px",
                    padding: "0 8px",
                    width: "100%",
                    marginBottom: "8px",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>
                    Tax Deducted Till Date (Current Employer)
                  </Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>0</Text>
                </View>
                <View
                  style={{
                    flexDirection: "row",
                    justifyContent: "flex-end",
                    gap: 20,
                    fontSize: "12px",
                    fontWeight: 500,
                    padding: 8,
                    backgroundColor: "rgba(83,55,255,0.05)",
                  }}
                >
                  <Text>Tax To Be Deducted This Year </Text>
                  <Text>0</Text>
                </View>
              </View>
            </View>
          </View>
          <View
            style={{
              display: "flex",
              flexDirection: "row",
              alignItems: "flex-start",
              marginBottom: "20px",
              padding: "0 12px",
            }}
          >
            <View style={{ width: "100%", marginTop: "25px" }}>
              <View
                style={{
                  display: "flex",
                  flexDirection: "row",
                  alignItems: "center",
                }}
              >
                <Text style={{ fontSize: "11px", fontWeight: "500" }}>
                  Tax for May 2025
                </Text>
                <Text
                  style={{
                    width: "5px",
                    height: "5px",
                    backgroundColor: "#1a36e5",
                    transform: "rotate(45deg)",
                    margin: "0 8px 0 8px",
                  }}
                ></Text>
                <Text
                  style={{
                    fontSize: "10px",
                    color: "#767473",
                    letterSpacing: "0.25px",
                  }}
                >
                  Tax to be deducted (F) / No. of payroll executions left in
                  this financial year
                </Text>
              </View>
              <View
                style={{
                  width: "100%",
                  fontSize: "12px",
                  overflow: "hidden",
                  marginTop: "10px",
                }}
              >
                <View
                  style={{
                    flexDirection: "row",
                    backgroundColor: "rgba(199,215,255,0.09)",
                    paddingVertical: 6,
                    paddingHorizontal: 12,
                    width: "100%",
                  }}
                >
                  <Text style={{ flex: 2, textAlign: "left" }}>
                    Tax to be deducted this month
                  </Text>
                  <Text style={{ flex: 1, textAlign: "right" }}>0</Text>
                </View>

                {/* Summary Row */}
                <View
                  style={{
                    flexDirection: "row",
                    justifyContent: "flex-end",
                    gap: 20,
                    fontWeight: 400,
                    padding: 8,
                    backgroundColor: "rgba(83,55,255,0.05)",
                  }}
                >
                  <Text>Tax Deducted This Month</Text>
                  <Text>0</Text>
                </View>
              </View>
            </View>
          </View>
          <View
            style={{
              display: "flex",
              flexDirection: "row",
              alignItems: "flex-start",
              marginBottom: "20px",
              position: "relative",
            }}
          >
            <Text
              style={{
                borderLeftWidth: 1.5,
                borderTopWidth: 1.5,
                width: "34px",
                marginTop: "6px",
                marginRight: "4px",
                height: "70%",
                borderColor: "#0826da",
                borderTopLeftRadius: 16,
              }}
            ></Text>
            <Text
              style={{
                width: "5px",
                height: "5px",
                backgroundColor: "#0826da",
                transform: "rotate(45deg)",
                margin: "0 8px 0 8px",
                position: "absolute",
                left: "-10px",
                bottom: "18px",
              }}
            ></Text>
            <View style={{ width: "100%" }}>
              <View
                style={{
                  display: "flex",
                  flexDirection: "row",
                  alignItems: "center",
                }}
              >
                <Text style={{ fontSize: "11px", fontWeight: "500" }}>
                  Monthly tax
                </Text>
                <Text
                  style={{
                    width: "5px",
                    height: "5px",
                    backgroundColor: "#0826da",
                    transform: "rotate(45deg)",
                    margin: "0 8px 0 8px",
                  }}
                ></Text>
                <Text
                  style={{
                    fontSize: "10px",
                    color: "#767473",
                    letterSpacing: "0.25px",
                  }}
                >
                  Projected TDS for rest of the year are marked with *
                </Text>
              </View>
              <View style={{ width: "100%", marginTop: "10px" }}>
                <View
                  style={{
                    flexDirection: "row",
                    justifyContent: "space-between",
                    marginBottom: "6px",
                    paddingHorizontal: 8,
                    color: "#8c8c8f",
                  }}
                >
                  {[
                    "April",
                    "May",
                    "June *",
                    "July *",
                    "August *",
                    "September *",
                  ].map((month, index) => (
                    <View key={index} style={{ flex: 1, paddingHorizontal: 4 }}>
                      <Text style={{ fontSize: 10 }}>{month} 2025</Text>
                      <Text style={{ fontSize: 11 }}>0</Text>
                    </View>
                  ))}
                </View>
                <View
                  style={{
                    flexDirection: "row",
                    justifyContent: "space-between",
                    paddingHorizontal: 8,
                    paddingVertical: 4,
                    backgroundColor: "rgba(176, 191, 252, 0.08)",
                  }}
                >
                  {[
                    "April",
                    "May",
                    "June *",
                    "July *",
                    "August *",
                    "September *",
                  ].map((month, index) => (
                    <View key={index} style={{ flex: 1, paddingHorizontal: 4 }}>
                      <Text style={{ fontSize: 11 }}>{month} 2025</Text>
                      <Text style={{ fontSize: 11 }}>0</Text>
                    </View>
                  ))}
                </View>
                <Text style={{ fontSize: "9px", color: "#b7b8bd" }}>
                  * These may change if there is a change in your income
                </Text>
              </View>
            </View>
          </View>
        </View>
      </Page>
    </Document>
  );
};

const PayslipPage = () => {
  const docRef = useRef(<PayslipDocument />);

  const handleDownload = async () => {
    const blob = await pdf(docRef.current).toBlob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "payslip.pdf";
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6">
      <div className="mb-6" style={{ height: "800px" }}>
        <PDFViewer width="100%" height="100%">
          <PayslipDocument />
        </PDFViewer>
      </div>

      <button
        onClick={handleDownload}
        className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700"
      >
        Download Payslip
      </button>
    </div>
  );
};

export default PayslipPage;
